# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8bac6891fdc6c7d353d563676052d5afdc0ada4e979aceb5276e4be4c0643f069dd1b3b01c2d5102350d1d3cda15e303d2b9469842ba297bc81df527f8eede1

test:
  secret_key_base: 886efa7b2c08979583b5b4428f67da0c3c61348526bfd825e404ff057a1ddfcd831771fac22c714a6dc2b0b7ae84d6cecb9a6cdd0426725bf33a3f6a4be98577

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
